GET http://localhost:4000/userdata/




###

GET http://localhost:4000/worldmap

###
POST http://localhost:4000/users/
Content-Type: application/json

{
    "name":"Eswar Vinay Venkatesh Pedagadi",
    "username":"rahul",
    "password":"rahul@2021",
    "gender":"Male",
    "location":"Rayavaram"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{"username":"rahul","password":"rahul@2021"}

###