GET https://a-u-t-h-e-n-t-i-c-a-t-i-o-n.herokuapp.com/userdata/




###


POST https://a-u-t-h-e-n-t-i-c-a-t-i-o-n.herokuapp.com/users/
Content-Type: application/json

{
    "name":"Sudh=eer",
    "username":"Sudher@365",
    "password":"Sudheer=@365",
    "gender":"Mae",
    "location":"Raavaram"
}

###

POST https://a-u-t-h-e-n-t-i-c-a-t-i-o-n.herokuapp.com/login
Content-Type: application/json

{"username":"Sudheer@365","password":"Sudheer@365"}

###